#include <STC12C5A.H>
	#pragma asm					//定义系统占用的内存区块，用于保存各任务现场数据
	/*TASK0_memory_section*/
	TASK0_PCL	XDATA	3FFH	//PC低八位
	TASK0_PCH	XDATA	3FEH	//PC高八位
	TASK0_ACC	XDATA   3FDH	//ACC累加器
	TASK0_B		XDATA	3FCH	//B累加器
	TASK0_DPH	XDATA	3FBH	//DPTR高八位
	TASK0_DPL	XDATA	3FAH	//DPTR低八位
	TASK0_PSW	XDATA	3F9H	//程序状态寄存器
	TASK0_AR0	XDATA	3F8H	//R0
	TASK0_AR1	XDATA	3F7H	//R1
	TASK0_AR2	XDATA   3F6H	//R2
	TASK0_AR3	XDATA	3F5H	//R3
	TASK0_AR4	XDATA	3F4H	//R4
	TASK0_AR5	XDATA	3F3H	//R5
	TASK0_AR6	XDATA	3F2H	//R6
	TASK0_AR7	XDATA	3F1H	//R7
	
	/*TASK1_memory_section*/
	TASK1_PCL	XDATA	3F0H
	TASK1_PCH	XDATA	3EFH
	TASK1_ACC	XDATA   3EEH
	TASK1_B		XDATA	3EDH
	TASK1_DPH	XDATA	3ECH
	TASK1_DPL	XDATA	3EBH
	TASK1_PSW	XDATA	3EAH
	TASK1_AR0	XDATA	3E9H
	TASK1_AR1	XDATA	3E8H
	TASK1_AR2	XDATA   3E7H
	TASK1_AR3	XDATA	3E6H
	TASK1_AR4	XDATA	3E5H
	TASK1_AR5	XDATA	3E4H
	TASK1_AR6	XDATA	3E3H
	TASK1_AR7	XDATA	3E2H
	
	/*TASK2_memory_section*/
	TASK2_PCL	XDATA	3E1H
	TASK2_PCH	XDATA	3E0H
	TASK2_ACC	XDATA   3DFH
	TASK2_B		XDATA	3DEH
	TASK2_DPH	XDATA	3DDH
	TASK2_DPL	XDATA	3DCH
	TASK2_PSW	XDATA	3DBH
	TASK2_AR0	XDATA	3DAH
	TASK2_AR1	XDATA	3D9H
	TASK2_AR2	XDATA   3D8H
	TASK2_AR3	XDATA	3D7H
	TASK2_AR4	XDATA	3D6H
	TASK2_AR5	XDATA	3D5H
	TASK2_AR6	XDATA	3D4H
	TASK2_AR7	XDATA	3D3H
	
	/*TASK3_memory_section*/
	TASK3_PCL	XDATA	3D2H
	TASK3_PCH	XDATA	3D1H
	TASK3_ACC	XDATA   3D0H
	TASK3_B		XDATA	3CFH
	TASK3_DPH	XDATA	3CEH
	TASK3_DPL	XDATA	3CDH
	TASK3_PSW	XDATA	3CCH
	TASK3_AR0	XDATA	3CBH
	TASK3_AR1	XDATA	3CAH
	TASK3_AR2	XDATA   3C9H
	TASK3_AR3	XDATA	3C8H
	TASK3_AR4	XDATA	3C7H
	TASK3_AR5	XDATA	3C6H
	TASK3_AR6	XDATA	3C5H
	TASK3_AR7	XDATA	3C4H
	
	/*TASK4_memory_section*/
	TASK4_PCL	XDATA	3C3H
	TASK4_PCH	XDATA	3C2H
	TASK4_ACC	XDATA   3C1H
	TASK4_B		XDATA	3C0H
	TASK4_DPH	XDATA	3BFH
	TASK4_DPL	XDATA	3BEH
	TASK4_PSW	XDATA	3BDH
	TASK4_AR0	XDATA	3BCH
	TASK4_AR1	XDATA	3BBH
	TASK4_AR2	XDATA   3BAH
	TASK4_AR3	XDATA	3B9H
	TASK4_AR4	XDATA	3B8H
	TASK4_AR5	XDATA	3B7H
	TASK4_AR6	XDATA	3B6H
	TASK4_AR7	XDATA	3B5H
	
	/*TASK5_memory_section*/
	TASK5_PCL	XDATA	3B4H
	TASK5_PCH	XDATA	3B3H
	TASK5_ACC	XDATA   3B2H
	TASK5_B		XDATA	3B1H
	TASK5_DPH	XDATA	3B0H
	TASK5_DPL	XDATA	3AFH
	TASK5_PSW	XDATA	3AEH
	TASK5_AR0	XDATA	3ADH
	TASK5_AR1	XDATA	3ACH
	TASK5_AR2	XDATA   3ABH
	TASK5_AR3	XDATA	3AAH
	TASK5_AR4	XDATA	3A9H
	TASK5_AR5	XDATA	3A8H
	TASK5_AR6	XDATA	3A7H
	TASK5_AR7	XDATA	3A6H	
#pragma endasm

void Tasks_Init(){
	#pragma asm
	/*task0 initialize:保存feed_dog PC低地址到0x3ff，高地址到0x3fe*/ 
	MOV		DPTR,	#Feed_Dog
	MOV		A,		DPL
	MOV		DPH,	#0x03
	MOV     DPL,	#0xFF
	MOVX	@DPTR,	A
	MOV		DPTR,	#Feed_Dog
	MOV		A,		DPH
	MOV		DPH,	#0x03
	MOV     DPL,	#0xFE
	MOVX	@DPTR,	A

	/*task1 initialize:保存button_action PC低地址到0x3f0，高地址到0x3ef*/
	MOV		DPTR,	#Button_Action
	MOV		A,		DPL
	MOV		DPH,	#0x03
	MOV     DPL,	#0xF0
	MOVX	@DPTR,	A
	MOV		DPTR,	#Button_Action
	MOV		A,		DPH
	MOV		DPH,	#0x03
	MOV     DPL,	#0xEF
	MOVX	@DPTR,	A

	/*task2 initialize:保存Refresh_MainPage PC低地址到0x3e1，高地址到0x3e0*/
	MOV		DPTR,	#Refresh_MainPage
	MOV		A,		DPL
	MOV		DPH,	#0x03
	MOV     DPL,	#0xE1
	MOVX	@DPTR,	A
	MOV		DPTR,	#Refresh_MainPage
	MOV		A,		DPH
	MOV		DPH,	#0x03
	MOV     DPL,	#0xE0
	MOVX	@DPTR,	A

	/*task3 initialize:保存Read_Temp PC低地址到0x3d2，高地址到0x3d1*/
	MOV		DPTR,	#Read_Temp
	MOV		A,		DPL
	MOV		DPH,	#0x03
	MOV     DPL,	#0xD2
	MOVX	@DPTR,	A
	MOV		DPTR,	#Read_Temp
	MOV		A,		DPH
	MOV		DPH,	#0x03
	MOV     DPL,	#0xD1
	MOVX	@DPTR,	A

	/*task4 initialize:保存State_Control PC低地址到0x3c3，高地址到0x3c2*/
	MOV		DPTR,	#State_Control
	MOV		A,		DPL
	MOV		DPH,	#0x03
	MOV     DPL,	#0xC3
	MOVX	@DPTR,	A
	MOV		DPTR,	#State_Control
	MOV		A,		DPH
	MOV		DPH,	#0x03
	MOV     DPL,	#0xC2
	MOVX	@DPTR,	A

	/*task5 initialize:保存EndCharging PC低地址到0x3b4，高地址到0x3b3*/
	MOV		DPTR,	#EndCharging
	MOV		A,		DPL
	MOV		DPH,	#0x03
	MOV     DPL,	#0xB4
	MOVX	@DPTR,	A
	MOV		DPTR,	#EndCharging
	MOV		A,		DPH
	MOV		DPH,	#0x03
	MOV     DPL,	#0xB3
	MOVX	@DPTR,	A
	#pragma endasm
}